# permissions for end users to edit autodeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autodep-editor-role
rules:
- apiGroups:
  - apps.autodep.com
  resources:
  - autodeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.autodep.com
  resources:
  - autodeps/status
  verbs:
  - get
