
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.autodep.com
  resources:
  - autodeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.autodep.com
  resources:
  - autodeps/finalizers
  verbs:
  - delete
  - update
- apiGroups:
  - apps.autodep.com
  resources:
  - autodeps/status
  verbs:
  - create
  - get
  - patch
  - update
